In [354]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [355]:
dataset = pd.read_csv('android-games.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [356]:
print(x)

[[1 'Garena Free Fire- World Series' 86273129 ... 3158756 2122183
  12495915]
 [2 'PUBG MOBILE - Traverse' 37276732 ... 1253185 809821 4709492]
 [3 'Mobile Legends: Bang Bang' 26663595 ... 1050600 713912 4308998]
 ...
 [98 'Scrabble® GO - New Word Game' 110723 ... 9385 6688 12132]
 [99 'Word Nut: Word Puzzle Games & Crosswords' 109530 ... 1469 953 2353]
 [100 'Pinturillo 2' 108917 ... 11825 6166 23631]]


In [357]:
print(y)

[False False False ... False False False]


In [358]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 2:3])
x[:, 2:3] = imputer.transform(x[:, 2:3])

In [359]:
print(x)

[[1 'Garena Free Fire- World Series' 86273129.0 ... 3158756 2122183
  12495915]
 [2 'PUBG MOBILE - Traverse' 37276732.0 ... 1253185 809821 4709492]
 [3 'Mobile Legends: Bang Bang' 26663595.0 ... 1050600 713912 4308998]
 ...
 [98 'Scrabble® GO - New Word Game' 110723.0 ... 9385 6688 12132]
 [99 'Word Nut: Word Puzzle Games & Crosswords' 109530.0 ... 1469 953
  2353]
 [100 'Pinturillo 2' 108917.0 ... 11825 6166 23631]]


In [360]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

c:\Python311\Lib\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [361]:
print(x)

[[1.0 0.0 0.0 ... 3158756 2122183 12495915]
 [0.0 1.0 0.0 ... 1253185 809821 4709492]
 [0.0 0.0 1.0 ... 1050600 713912 4308998]
 ...
 [0.0 0.0 0.0 ... 9385 6688 12132]
 [0.0 0.0 0.0 ... 1469 953 2353]
 [0.0 0.0 0.0 ... 11825 6166 23631]]


In [362]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [363]:
print(y)

[0 0 0 ... 0 0 0]


In [364]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [365]:
print(x_train)

[[0.0 0.0 0.0 ... 1971 1139 3487]
 [0.0 0.0 0.0 ... 433227 128489 288631]
 [0.0 0.0 0.0 ... 31975 20348 100402]
 ...
 [0.0 0.0 0.0 ... 25508 10219 27348]
 [0.0 0.0 0.0 ... 97115 38288 173823]
 [0.0 0.0 0.0 ... 25613 9960 28395]]


In [366]:
print(x_test)

[[0.0 0.0 0.0 ... 106587 61626 221936]
 [0.0 0.0 0.0 ... 14384 5285 12447]
 [0.0 0.0 0.0 ... 3313 1247 4311]
 ...
 [0.0 0.0 0.0 ... 7028 2559 9397]
 [0.0 0.0 0.0 ... 131708 84146 327675]
 [0.0 0.0 0.0 ... 31524 15502 54414]]


In [367]:
print(y_train)

[0 0 0 ... 0 0 0]


In [368]:
print(y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [369]:
import pandas as pd

categorical_cols = [3]
x_train_categorical = x_train[:, categorical_cols]
x_test_categorical = x_test[:, categorical_cols]

ohe = pd.get_dummies(pd.concat([pd.DataFrame(x_train_categorical), pd.DataFrame(x_test_categorical)]))
x_train_ohe = ohe[:len(x_train_categorical)]
x_test_ohe = ohe[len(x_train_categorical):]

x_train_processed = np.hstack((x_train[:, :3], x_train_ohe.values, x_train[:, 4:]))
x_test_processed = np.hstack((x_test[:, :3], x_test_ohe.values, x_test[:, 4:]))

C:\Users\admin\AppData\Local\Temp\ipykernel_412\2187101010.py:7: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  ohe = pd.get_dummies(pd.concat([pd.DataFrame(x_train_categorical), pd.DataFrame(x_test_categorical)]))


In [370]:
print(x_train)

[[0.0 0.0 0.0 ... 1971 1139 3487]
 [0.0 0.0 0.0 ... 433227 128489 288631]
 [0.0 0.0 0.0 ... 31975 20348 100402]
 ...
 [0.0 0.0 0.0 ... 25508 10219 27348]
 [0.0 0.0 0.0 ... 97115 38288 173823]
 [0.0 0.0 0.0 ... 25613 9960 28395]]


In [371]:
print(x_test)

[[0.0 0.0 0.0 ... 106587 61626 221936]
 [0.0 0.0 0.0 ... 14384 5285 12447]
 [0.0 0.0 0.0 ... 3313 1247 4311]
 ...
 [0.0 0.0 0.0 ... 7028 2559 9397]
 [0.0 0.0 0.0 ... 131708 84146 327675]
 [0.0 0.0 0.0 ... 31524 15502 54414]]
